export const BOT_CHANNEL_ADAPTER = Symbol('BOT_CHANNEL_ADAPTER');
export const ZCA_CHANNEL_ADAPTER = Symbol('ZCA_CHANNEL_ADAPTER');
export const MOCK_CHANNEL_ADAPTER = Symbol('MOCK_CHANNEL_ADAPTER');
