import { Injectable } from '@nestjs/common';
import type { PrismaService } from '../../config/prisma.service.js';
import type { BusinessDate } from '../business-date.js';
import { fromStoredAmount, toStoredAmount } from '../money.js';
import { TransportDomainError } from '../transport.errors.js';
import { allocationBalance, differenceAmount, reconciliationGross } from './customer-ar-documents.js';
import { CustomerArRepository } from './customer-ar.repository.js';
import type {
  AllocatePaymentCommand,
  ConfirmOrderReconciliationCommand,
  CreateReconciliationBatchCommand,
  DeferBatchLineCommand,
  RecordPaymentCommand,
  ReleasePaymentAllocationCommand,
} from './customer-ar.repository.js';
import type {
  CustomerPayment,
  CustomerPaymentAllocation,
  CustomerPaymentBalance,
  CustomerReceivablePosition,
  CustomerReconciliation,
  CustomerReconciliationBatch,
  CustomerReconciliationBatchLine,
  PendingReconciliationOrder,
} from './customer-ar.types.js';

/* Prisma Client is regenerated by CI after the additive migration. Dynamic model lookup keeps this
 * file usable during that bootstrap while retaining typed public domain boundaries. */
/* eslint-disable @typescript-eslint/no-explicit-any */
const model = (client: unknown, name: string): any =>
  (client as Record<string, any>)[name];
const amount = (stored: bigint): number => fromStoredAmount(stored) ?? 0;
const iso = (value: Date): string => value.toISOString();
const dateStatus = (
  outstanding: number,
  dueDate: BusinessDate | null,
  asOf: BusinessDate,
): CustomerReceivablePosition['status'] => {
  if (outstanding === 0) return 'PAID';
  if (dueDate === asOf) return 'DUE';
  if (dueDate !== null && dueDate < asOf) return 'OVERDUE';
  return 'NOT_YET_DUE';
};

const toReconciliation = (row: any): CustomerReconciliation => ({
  id: row.id,
  orderId: row.orderId,
  customerId: row.customerId,
  batchLineId: row.batchLineId,
  proposedAmount: amount(row.proposedAmount),
  confirmedAmount: amount(row.confirmedAmount),
  differenceAmount: amount(row.differenceAmount),
  currencyCode: row.currencyCode,
  businessDate: row.businessDate,
  dueDate: row.dueDate,
  differenceReason: row.differenceReason,
  confirmationReference: row.confirmationReference,
  evidenceRefs: row.evidenceRefs,
  sourceId: row.sourceId,
  sourceFingerprint: row.sourceFingerprint,
  confirmedBy: row.confirmedBy,
  confirmedAt: iso(row.confirmedAt),
  settlementDocumentId: row.settlementDocumentId,
});

const toBatchLine = (row: any): CustomerReconciliationBatchLine => ({
  id: row.id,
  batchId: row.batchId,
  orderId: row.orderId,
  orderCode: row.orderCode,
  proposedAmount: amount(row.proposedAmount),
  currencyCode: row.currencyCode,
  state: row.state,
  resolutionReason: row.resolutionReason,
  resolvedBy: row.resolvedBy,
  resolvedAt: row.resolvedAt ? iso(row.resolvedAt) : null,
  resolutionSourceId: row.resolutionSourceId,
  reconciliationId: row.reconciliation?.id ?? null,
});

const toBatch = (row: any): CustomerReconciliationBatch => ({
  id: row.id,
  customerId: row.customerId,
  currencyCode: row.currencyCode,
  status: row.status,
  periodStart: row.periodStart,
  periodEnd: row.periodEnd,
  reference: row.reference,
  note: row.note,
  sourceId: row.sourceId,
  sourceFingerprint: row.sourceFingerprint,
  createdBy: row.createdBy,
  createdAt: iso(row.createdAt),
  closedBy: row.closedBy,
  closedAt: row.closedAt ? iso(row.closedAt) : null,
  lines: (row.lines ?? []).map(toBatchLine),
});

const toPayment = (row: any): CustomerPayment => ({
  id: row.id,
  customerId: row.customerId,
  amount: amount(row.amount),
  currencyCode: row.currencyCode,
  receivedAt: iso(row.receivedAt),
  businessDate: row.businessDate,
  externalRef: row.externalRef,
  note: row.note,
  recordedBy: row.recordedBy,
  sourceId: row.sourceId,
  sourceFingerprint: row.sourceFingerprint,
  createdAt: iso(row.createdAt),
});

const toAllocation = (row: any): CustomerPaymentAllocation => ({
  id: row.id,
  paymentId: row.paymentId,
  documentId: row.documentId,
  kind: row.kind,
  amount: amount(row.amount),
  businessDate: row.businessDate,
  reversesId: row.reversesId,
  sourceId: row.sourceId,
  sourceFingerprint: row.sourceFingerprint,
  note: row.note,
  recordedBy: row.recordedBy,
  createdAt: iso(row.createdAt),
});

const assertReplay = (actual: string, expected: string, reason: Parameters<typeof TransportDomainError.denied>[0]): void => {
  if (actual !== expected) throw TransportDomainError.denied(reason, 'Khoa idempotency da duoc ghi voi noi dung kinh te khac');
};

@Injectable()
export class PrismaCustomerArRepository extends CustomerArRepository {
  constructor(private readonly prisma: PrismaService) { super(); }

  private async transaction<T>(work: (tx: any) => Promise<T>): Promise<T> {
    return this.prisma.$transaction(work, { isolationLevel: 'ReadCommitted' });
  }

  private async idempotencyLock(tx: any, context: string, id: string): Promise<void> {
    await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${`${context}:${id}`}, 0))`;
  }

  private async assertPeriodWritable(tx: any, businessDate: BusinessDate): Promise<void> {
    await tx.$executeRaw`SELECT pg_advisory_xact_lock(hashtextextended(${'settlement-period:CUSTOMER_FREIGHT'}, 0))`;
    const frozen = await model(tx, 'transportSettlementPeriod').findFirst({ where: {
      flow: 'CUSTOMER_FREIGHT', status: { in: ['CLOSING', 'CLOSED'] },
      startDate: { lte: businessDate }, endDate: { gte: businessDate },
    } });
    if (frozen) throw TransportDomainError.denied('SETTLEMENT_PERIOD_FROZEN', 'Ky phai thu khach da dong bang');
  }

  async pendingOrders(customerId?: string): Promise<PendingReconciliationOrder[]> {
    const rows = await model(this.prisma, 'transportOrder').findMany({
      where: {
        status: 'FULFILLED', customerId: customerId ? customerId : { not: null }, freightAmount: { not: null },
        completion: { is: { state: 'APPROVED' } }, customerReconciliation: { is: null },
      }, orderBy: [{ businessDate: 'asc' }, { code: 'asc' }],
    });
    return rows.map((row: any) => ({ orderId: row.id, orderCode: row.code, customerId: row.customerId,
      proposedAmount: amount(row.freightAmount), currencyCode: row.currencyCode, businessDate: row.businessDate }));
  }

  async confirmOrder(command: ConfirmOrderReconciliationCommand) {
    return this.transaction(async (tx) => {
      await this.idempotencyLock(tx, command.sourceContext, command.sourceId);
      const existing = await model(tx, 'transportCustomerReconciliation').findUnique({
        where: { sourceContext_sourceId: { sourceContext: command.sourceContext, sourceId: command.sourceId } },
      });
      if (existing) { assertReplay(existing.sourceFingerprint, command.sourceFingerprint, 'CUSTOMER_AR_SOURCE_FINGERPRINT_CONFLICT'); return { reconciliation: toReconciliation(existing), replayed: true }; }

      // One global order: period -> Order -> batch line -> settlement document. The raw SQL
      // guards use the same order, so period closing cannot deadlock with a confirmation.
      await this.assertPeriodWritable(tx, command.businessDate);
      await tx.$executeRaw`SELECT "id" FROM "TransportOrder" WHERE "id" = ${command.orderId} FOR UPDATE`;
      const order = await model(tx, 'transportOrder').findUnique({
        where: { id: command.orderId }, include: { completion: true, customerReconciliation: true },
      });
      if (!order) throw TransportDomainError.notFound('CUSTOMER_AR_ORDER_NOT_FOUND', `Khong thay don ${command.orderId}`);
      if (order.status !== 'FULFILLED' || order.completion?.state !== 'APPROVED' || !order.customerId || order.freightAmount === null)
        throw TransportDomainError.denied('CUSTOMER_AR_ORDER_NOT_ELIGIBLE', 'Don chua du dieu kien doi soat');
      if (amount(order.freightAmount) !== command.proposedAmount) throw TransportDomainError.denied('CUSTOMER_AR_PROPOSED_AMOUNT_MISMATCH', 'So tien de nghi phai lay tu Order da khoa');
      if (order.customerReconciliation) throw TransportDomainError.conflict('CUSTOMER_AR_ORDER_ALREADY_CONFIRMED', 'Don da duoc A xac nhan');
      if (order.currencyCode !== command.currencyCode) throw TransportDomainError.denied('CUSTOMER_AR_CURRENCY_MISMATCH', 'Loai tien khong khop don');

      const pendingLine = await model(tx, 'transportCustomerReconciliationBatchLine').findFirst({
        where: { orderId: order.id, state: 'PENDING' }, select: { id: true },
      });
      if (!command.batchLineId && pendingLine) {
        throw TransportDomainError.conflict('CUSTOMER_AR_ORDER_ALREADY_IN_BATCH', 'Don dang nam trong batch doi soat; A phai xu ly dong batch');
      }
      if (command.batchLineId) {
        await tx.$executeRaw`SELECT "id" FROM "TransportCustomerReconciliationBatchLine" WHERE "id" = ${command.batchLineId} FOR UPDATE`;
        const line = await model(tx, 'transportCustomerReconciliationBatchLine').findUnique({ where: { id: command.batchLineId }, include: { batch: true } });
        if (!line) throw TransportDomainError.notFound('CUSTOMER_AR_BATCH_LINE_NOT_FOUND', 'Khong thay dong batch');
        if (line.state !== 'PENDING') throw TransportDomainError.conflict('CUSTOMER_AR_BATCH_LINE_ALREADY_RESOLVED', 'Dong batch da duoc xu ly');
        if (line.orderId !== order.id || line.batch.customerId !== order.customerId) throw TransportDomainError.denied('CUSTOMER_AR_BATCH_CUSTOMER_MISMATCH', 'Don khong thuoc batch/customer');
        if (line.currencyCode !== command.currencyCode || line.batch.currencyCode !== command.currencyCode) throw TransportDomainError.denied('CUSTOMER_AR_BATCH_CURRENCY_MISMATCH', 'Loai tien batch khong khop');
        if (line.batch.status !== 'DRAFT') throw TransportDomainError.denied('CUSTOMER_AR_BATCH_NOT_DRAFT', 'Batch khong con mo');
      }

      const previousDocument = await model(tx, 'transportSettlementDocument').findUnique({
        where: { sourceContext_sourceId: { sourceContext: command.document.sourceContext, sourceId: command.document.sourceId } },
      });
      if (previousDocument) throw TransportDomainError.conflict('CUSTOMER_AR_ORDER_ALREADY_CONFIRMED', 'Nguon settlement da ton tai ma reconciliation khong ton tai');
      const document = await model(tx, 'transportSettlementDocument').create({ data: {
        ...command.document, signedAmount: toStoredAmount(command.document.signedAmount), kind: 'ORIGINAL', status: 'POSTED', adjustsId: null,
      }});
      const row = await model(tx, 'transportCustomerReconciliation').create({ data: {
        orderId: command.orderId, customerId: order.customerId, batchLineId: command.batchLineId,
        proposedAmount: toStoredAmount(command.proposedAmount), confirmedAmount: toStoredAmount(command.confirmedAmount),
        differenceAmount: toStoredAmount(differenceAmount(command.proposedAmount, command.confirmedAmount)),
        currencyCode: command.currencyCode, businessDate: command.businessDate, dueDate: command.dueDate,
        differenceReason: command.differenceReason, confirmationReference: command.confirmationReference,
        evidenceRefs: [...command.evidenceRefs], sourceContext: command.sourceContext, sourceId: command.sourceId,
        sourceFingerprint: command.sourceFingerprint, confirmedBy: command.confirmedBy, settlementDocumentId: document.id,
      }});
      if (command.batchLineId) await model(tx, 'transportCustomerReconciliationBatchLine').update({ where: { id: command.batchLineId }, data: {
        state: 'CONFIRMED', resolvedBy: command.confirmedBy, resolvedAt: new Date(), resolutionSourceId: command.sourceId,
        resolutionFingerprint: command.sourceFingerprint,
      }});
      return { reconciliation: toReconciliation(row), replayed: false };
    });
  }

  async createBatch(command: CreateReconciliationBatchCommand) {
    return this.transaction(async (tx) => {
      await this.idempotencyLock(tx, command.sourceContext, command.sourceId);
      const existing = await model(tx, 'transportCustomerReconciliationBatch').findUnique({
        where: { sourceContext_sourceId: { sourceContext: command.sourceContext, sourceId: command.sourceId } }, include: { lines: { include: { reconciliation: true } } },
      });
      if (existing) { assertReplay(existing.sourceFingerprint, command.sourceFingerprint, 'CUSTOMER_AR_SOURCE_FINGERPRINT_CONFLICT'); return { batch: toBatch(existing), replayed: true }; }
      if (new Set(command.orderIds).size !== command.orderIds.length || command.orderIds.length === 0) throw TransportDomainError.invalid('CUSTOMER_AR_ORDER_NOT_ELIGIBLE', 'Batch phai co danh sach don duy nhat');
      const customer = await model(tx, 'transportCustomer').findUnique({ where: { id: command.customerId } });
      if (!customer) throw TransportDomainError.notFound('CUSTOMER_AR_ORDER_NOT_FOUND', 'Khong thay khach hang');
      for (const orderId of [...command.orderIds].sort()) {
        await tx.$executeRaw`SELECT "id" FROM "TransportOrder" WHERE "id" = ${orderId} FOR UPDATE`;
      }
      const orders = await model(tx, 'transportOrder').findMany({ where: { id: { in: [...command.orderIds] } }, include: { completion: true, customerReconciliation: true } });
      if (orders.length !== command.orderIds.length || orders.some((order: any) => order.status !== 'FULFILLED' || order.completion?.state !== 'APPROVED' || order.customerId !== command.customerId || order.freightAmount === null || order.customerReconciliation))
        throw TransportDomainError.denied('CUSTOMER_AR_ORDER_NOT_ELIGIBLE', 'Batch co don chua san sang doi soat');
      if (orders.some((order: any) => order.currencyCode !== command.currencyCode)) throw TransportDomainError.denied('CUSTOMER_AR_BATCH_CURRENCY_MISMATCH', 'Batch chi chua mot loai tien');
      const pendingLines = await model(tx, 'transportCustomerReconciliationBatchLine').findFirst({
        where: { orderId: { in: [...command.orderIds] }, state: 'PENDING' },
      });
      if (pendingLines) throw TransportDomainError.conflict('CUSTOMER_AR_ORDER_ALREADY_IN_BATCH', 'Don da nam trong mot batch dang mo');
      const row = await model(tx, 'transportCustomerReconciliationBatch').create({ data: {
        customerId: command.customerId, currencyCode: command.currencyCode, status: 'DRAFT', periodStart: command.periodStart,
        periodEnd: command.periodEnd, reference: command.reference, note: command.note, sourceContext: command.sourceContext,
        sourceId: command.sourceId, sourceFingerprint: command.sourceFingerprint, createdBy: command.createdBy,
        lines: { create: orders.map((order: any) => ({ orderId: order.id, orderCode: order.code, proposedAmount: order.freightAmount, currencyCode: order.currencyCode })) },
      }, include: { lines: { include: { reconciliation: true } } } });
      return { batch: toBatch(row), replayed: false };
    });
  }

  async deferBatchLine(command: DeferBatchLineCommand): Promise<CustomerReconciliationBatch> {
    return this.transaction(async (tx) => {
      await tx.$executeRaw`SELECT "id" FROM "TransportCustomerReconciliationBatchLine" WHERE "id" = ${command.lineId} FOR UPDATE`;
      const line = await model(tx, 'transportCustomerReconciliationBatchLine').findUnique({ where: { id: command.lineId } });
      if (!line || line.batchId !== command.batchId) throw TransportDomainError.notFound('CUSTOMER_AR_BATCH_LINE_NOT_FOUND', 'Khong thay dong batch');
      if (line.state !== 'PENDING') {
        if (line.state === 'DEFERRED' && line.resolutionSourceId === command.sourceId) { assertReplay(line.resolutionFingerprint, command.sourceFingerprint, 'CUSTOMER_AR_SOURCE_FINGERPRINT_CONFLICT'); return (await this.findBatchIn(tx, command.batchId))!; }
        throw TransportDomainError.conflict('CUSTOMER_AR_BATCH_LINE_ALREADY_RESOLVED', 'Dong batch da duoc xu ly');
      }
      const batch = await model(tx, 'transportCustomerReconciliationBatch').findUnique({ where: { id: command.batchId } });
      if (!batch) throw TransportDomainError.notFound('CUSTOMER_AR_BATCH_NOT_FOUND', 'Khong thay batch');
      if (batch.status !== 'DRAFT') throw TransportDomainError.denied('CUSTOMER_AR_BATCH_NOT_DRAFT', 'Batch khong con mo');
      await model(tx, 'transportCustomerReconciliationBatchLine').update({ where: { id: command.lineId }, data: {
        state: 'DEFERRED', resolutionReason: command.reason, resolvedBy: command.actor, resolvedAt: new Date(),
        resolutionSourceId: command.sourceId, resolutionFingerprint: command.sourceFingerprint,
      }});
      return (await this.findBatchIn(tx, command.batchId))!;
    });
  }

  async closeBatch(batchId: string, actor: string): Promise<CustomerReconciliationBatch> {
    return this.transaction(async (tx) => {
      await tx.$executeRaw`SELECT "id" FROM "TransportCustomerReconciliationBatch" WHERE "id" = ${batchId} FOR UPDATE`;
      const batch = await model(tx, 'transportCustomerReconciliationBatch').findUnique({ where: { id: batchId }, include: { lines: true } });
      if (!batch) throw TransportDomainError.notFound('CUSTOMER_AR_BATCH_NOT_FOUND', 'Khong thay batch');
      if (batch.status === 'CLOSED') return (await this.findBatchIn(tx, batchId))!;
      if (batch.status !== 'DRAFT') throw TransportDomainError.denied('CUSTOMER_AR_BATCH_NOT_DRAFT', 'Batch khong con mo');
      if (batch.lines.some((line: any) => line.state === 'PENDING')) throw TransportDomainError.denied('CUSTOMER_AR_BATCH_NOT_DRAFT', 'Batch con dong chua xu ly');
      await model(tx, 'transportCustomerReconciliationBatch').update({ where: { id: batchId }, data: { status: 'CLOSED', closedBy: actor, closedAt: new Date() } });
      return (await this.findBatchIn(tx, batchId))!;
    });
  }

  private async findBatchIn(tx: unknown, id: string): Promise<CustomerReconciliationBatch | null> {
    const row = await model(tx, 'transportCustomerReconciliationBatch').findUnique({ where: { id }, include: { lines: { include: { reconciliation: true }, orderBy: [{ createdAt: 'asc' }, { id: 'asc' }] } } });
    return row ? toBatch(row) : null;
  }
  async findBatch(id: string) { return this.findBatchIn(this.prisma, id); }
  async listBatches(customerId?: string) { const rows = await model(this.prisma, 'transportCustomerReconciliationBatch').findMany({ where: customerId ? { customerId } : {}, include: { lines: { include: { reconciliation: true } } }, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }] }); return rows.map(toBatch); }

  async recordPayment(command: RecordPaymentCommand) {
    return this.transaction(async (tx) => {
      await this.idempotencyLock(tx, command.sourceContext, command.sourceId);
      const existing = await model(tx, 'transportCustomerPayment').findUnique({ where: { sourceContext_sourceId: { sourceContext: command.sourceContext, sourceId: command.sourceId } } });
      if (existing) { assertReplay(existing.sourceFingerprint, command.sourceFingerprint, 'CUSTOMER_PAYMENT_SOURCE_FINGERPRINT_CONFLICT'); return { payment: toPayment(existing), replayed: true }; }
      await this.assertPeriodWritable(tx, command.businessDate);
      const customer = await model(tx, 'transportCustomer').findUnique({ where: { id: command.customerId } });
      if (!customer) throw TransportDomainError.notFound('CUSTOMER_AR_CUSTOMER_NOT_FOUND', 'Khong thay khach hang cua payment');
      const row = await model(tx, 'transportCustomerPayment').create({ data: { ...command, amount: toStoredAmount(command.amount) } });
      return { payment: toPayment(row), replayed: false };
    });
  }

  async allocatePayment(command: AllocatePaymentCommand) {
    return this.transaction(async (tx) => {
      await this.idempotencyLock(tx, command.sourceContext, command.sourceId);
      const existing = await model(tx, 'transportCustomerPaymentAllocation').findUnique({ where: { sourceContext_sourceId: { sourceContext: command.sourceContext, sourceId: command.sourceId } } });
      if (existing) { assertReplay(existing.sourceFingerprint, command.sourceFingerprint, 'CUSTOMER_PAYMENT_ALLOCATION_SOURCE_FINGERPRINT_CONFLICT'); return { allocation: toAllocation(existing), replayed: true }; }
      await this.assertPeriodWritable(tx, command.businessDate);
      await tx.$executeRaw`SELECT "id" FROM "TransportCustomerPayment" WHERE "id" = ${command.paymentId} FOR UPDATE`;
      await tx.$executeRaw`SELECT "id" FROM "TransportSettlementDocument" WHERE "id" = ${command.documentId} FOR UPDATE`;
      const payment = await model(tx, 'transportCustomerPayment').findUnique({ where: { id: command.paymentId } });
      if (!payment) throw TransportDomainError.notFound('CUSTOMER_PAYMENT_NOT_FOUND', 'Khong thay payment');
      const document = await model(tx, 'transportSettlementDocument').findUnique({ where: { id: command.documentId } });
      if (!document || document.kind !== 'ORIGINAL' || document.status !== 'POSTED' || document.direction !== 'RECEIVABLE' || document.flow !== 'CUSTOMER_FREIGHT') throw TransportDomainError.notFound('CUSTOMER_AR_RECEIVABLE_NOT_FOUND', 'Khong thay cong no khach chinh thuc');
      if (payment.customerId !== document.counterpartyId) throw TransportDomainError.denied('CUSTOMER_AR_CUSTOMER_MISMATCH', 'Payment va cong no khac khach');
      if (payment.currencyCode !== document.currencyCode) throw TransportDomainError.denied('CUSTOMER_AR_CURRENCY_MISMATCH', 'Payment va cong no khac loai tien');
      const [paymentRows, chainRows, legacyRows, documentRows] = await Promise.all([
        model(tx, 'transportCustomerPaymentAllocation').findMany({ where: { paymentId: command.paymentId } }),
        model(tx, 'transportCustomerPaymentAllocation').findMany({ where: { documentId: command.documentId } }),
        model(tx, 'transportSettlementAllocation').findMany({ where: { documentId: command.documentId } }),
        model(tx, 'transportSettlementDocument').findMany({ where: { OR: [{ id: command.documentId }, { adjustsId: command.documentId }], status: 'POSTED' } }),
      ]);
      const paymentUsed = allocationBalance(paymentRows.map((row: any) => ({ kind: row.kind, amount: amount(row.amount) })));
      if (paymentUsed + command.amount > amount(payment.amount)) throw TransportDomainError.denied('CUSTOMER_PAYMENT_ALLOCATION_EXCEEDS_BALANCE', 'Phan bo vuot payment chua dung');
      const allocated = legacyRows.reduce((sum: number, row: any) => sum + amount(row.amount), 0) + allocationBalance(chainRows.map((row: any) => ({ kind: row.kind, amount: amount(row.amount) })));
      const gross = reconciliationGross(documentRows.map((row: any) => amount(row.signedAmount)));
      if (allocated + command.amount > gross) throw TransportDomainError.denied('CUSTOMER_PAYMENT_ALLOCATION_EXCEEDS_OUTSTANDING', 'Phan bo vuot cong no con lai');
      const row = await model(tx, 'transportCustomerPaymentAllocation').create({ data: { ...command, kind: 'APPLY', amount: toStoredAmount(command.amount), reversesId: null } });
      return { allocation: toAllocation(row), replayed: false };
    });
  }

  async releaseAllocation(command: ReleasePaymentAllocationCommand) {
    return this.transaction(async (tx) => {
      await this.idempotencyLock(tx, command.sourceContext, command.sourceId);
      const existing = await model(tx, 'transportCustomerPaymentAllocation').findUnique({ where: { sourceContext_sourceId: { sourceContext: command.sourceContext, sourceId: command.sourceId } } });
      if (existing) { assertReplay(existing.sourceFingerprint, command.sourceFingerprint, 'CUSTOMER_PAYMENT_ALLOCATION_SOURCE_FINGERPRINT_CONFLICT'); return { allocation: toAllocation(existing), replayed: true }; }
      await this.assertPeriodWritable(tx, command.businessDate);
      await tx.$executeRaw`SELECT "id" FROM "TransportCustomerPaymentAllocation" WHERE "id" = ${command.allocationId} FOR UPDATE`;
      const target = await model(tx, 'transportCustomerPaymentAllocation').findUnique({ where: { id: command.allocationId }, include: { releasedBy: true } });
      if (!target || target.kind !== 'APPLY') throw TransportDomainError.notFound('CUSTOMER_PAYMENT_ALLOCATION_NOT_FOUND', 'Khong thay phan bo goc');
      if (target.releasedBy) throw TransportDomainError.conflict('CUSTOMER_PAYMENT_ALLOCATION_ALREADY_RELEASED', 'Phan bo da duoc release');
      const row = await model(tx, 'transportCustomerPaymentAllocation').create({ data: {
        paymentId: target.paymentId, documentId: target.documentId, kind: 'RELEASE', amount: target.amount,
        businessDate: command.businessDate, reversesId: target.id, sourceContext: command.sourceContext,
        sourceId: command.sourceId, sourceFingerprint: command.sourceFingerprint, note: command.note, recordedBy: command.recordedBy,
      }});
      return { allocation: toAllocation(row), replayed: false };
    });
  }

  async findReconciliationByOrder(orderId: string) { const row = await model(this.prisma, 'transportCustomerReconciliation').findUnique({ where: { orderId } }); return row ? toReconciliation(row) : null; }
  async findPayment(id: string) { const row = await model(this.prisma, 'transportCustomerPayment').findUnique({ where: { id } }); return row ? toPayment(row) : null; }
  async paymentBalance(id: string): Promise<CustomerPaymentBalance | null> {
    const row = await model(this.prisma, 'transportCustomerPayment').findUnique({ where: { id }, include: { allocations: { orderBy: [{ createdAt: 'asc' }, { id: 'asc' }] } } });
    if (!row) return null; const allocations = row.allocations.map(toAllocation); const allocatedAmount = allocationBalance(allocations);
    return { payment: toPayment(row), allocations, allocatedAmount, unallocatedAmount: amount(row.amount) - allocatedAmount };
  }
  async listPaymentBalances(customerId?: string) { const rows = await model(this.prisma, 'transportCustomerPayment').findMany({ where: customerId ? { customerId } : {}, orderBy: [{ businessDate: 'asc' }, { id: 'asc' }] }); const values = await Promise.all(rows.map((row: any) => this.paymentBalance(row.id))); return values.filter((value): value is CustomerPaymentBalance => value !== null); }

  async listReceivablePositions(asOf: BusinessDate, customerId?: string): Promise<CustomerReceivablePosition[]> {
    const originals = await model(this.prisma, 'transportSettlementDocument').findMany({ where: { direction: 'RECEIVABLE', flow: 'CUSTOMER_FREIGHT', kind: 'ORIGINAL', ...(customerId ? { counterpartyId: customerId } : {}) }, include: { customerReconciliation: true, allocations: true, customerPaymentAllocations: true }, orderBy: [{ businessDate: 'asc' }, { id: 'asc' }] });
    return Promise.all(originals.map(async (root: any) => {
      const corrections = await model(this.prisma, 'transportSettlementDocument').findMany({ where: { adjustsId: root.id, status: 'POSTED' } });
      const grossAmount = reconciliationGross([root, ...corrections].map((row: any) => amount(row.signedAmount)));
      const allocatedAmount = root.allocations.reduce((sum: number, row: any) => sum + amount(row.amount), 0) + allocationBalance(root.customerPaymentAllocations.map((row: any) => ({ kind: row.kind, amount: amount(row.amount) })));
      const outstandingAmount = Math.max(0, grossAmount - allocatedAmount);
      return { reconciliation: root.customerReconciliation ? toReconciliation(root.customerReconciliation) : null, documentId: root.id, customerId: root.counterpartyId, currencyCode: root.currencyCode, grossAmount, allocatedAmount, outstandingAmount, dueDate: root.dueDate, status: dateStatus(outstandingAmount, root.dueDate, asOf) };
    }));
  }
}
